name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Zig 0.15.2
        run: |
          ZIG_VERSION=0.15.2
          ZIG_ARCHIVE=zig-linux-x86_64-${ZIG_VERSION}.tar.xz
          curl -fL https://ziglang.org/download/${ZIG_VERSION}/${ZIG_ARCHIVE} -o ${ZIG_ARCHIVE}
          tar -xf ${ZIG_ARCHIVE}
          echo "${PWD}/zig-linux-x86_64-${ZIG_VERSION}" >> "${GITHUB_PATH}"

      - name: Zig Version
        run: zig version

      - name: Format
        run: zig fmt .

      - name: Build
        run: zig build

      - name: Test
        run: zig test src/main.zig
